### ISSUE TITLE
License Numbers and Privacy Policy

### ISSUE THREAD

**Issue by Noble-Mushtak** [brianjaustin/permitlog-android#42]
We are currently storing the accompanying driver's license number, which is pretty sensitive information and [can lead to identity theft if stolen](http://www.idtheftcenter.org/Identity-Theft/can-someone-steal-your-identity-from-your-driver-s-license.html). A few people have talked about this in reviews of the app, such as [here](https://play.google.com/store/apps/details?id=team.tr.permitlog&reviewId=Z3A6QU9xcFRPSFFIZlNEY2laYVRrMDJoYmljc01rVnItVG1rM0d3dGRaUzZGSjRLYmdQdy0yX0JhMzJsaktEWDh4Uy1jV19uRGt3VE43cXgxcjRfQzJ3X2c&hl=en), [here](https://play.google.com/store/apps/details?id=team.tr.permitlog&reviewId=Z3A6QU9xcFRPSFFIZlNEY2laYVRrMDJoYmljc01rVnItVG1rM0d3dGRaUzZGSjRLYmdQdy0yX0JhMzJsaktEWDh4Uy1jV19uRGt3VE43cXgxcjRfQzJ3X2c&hl=en), and [here](https://play.google.com/store/apps/details?id=team.tr.permitlog&reviewId=Z3A6QU9xcFRPRnFaSncwQm5GejE3SVVqQk9VY1c3dmp3SEttekFsQ1ktXzdNYXFKWUpzLWFiSTc1Y1BDcUpNcnFfdnBVcEtYYWJGYzJmektNeE9oQWIycHc&hl=en). Four issues readily come to mind here:

- [x] 1. As one of the reviews mentioned, the license number can't just be a number. In some states like [Washington](http://www.highprogrammer.com/alan/numbers/dl_us_wa.html), the license ID contains letters and special characters like asterisks, too.
- [x] 2. We need to make the driver's license optional: If they leave this field blank, we should warn them that they left it blank and if they confirm that this was on purpose, then when they export their log, the driver license field on the sheet will be left blank.
- [ ] 3. We need to encrypt the user's data. Arguably, even we shouldn't have access to this kind of personal information, although I'm not sure how we should implement this.
- [x] 4. We need to have a privacy policy for legal reasons and so that users know how their sensitive information is being treated. Personally, I got my Web site's privacy policy from [an online generator](https://privacypolicies.com/), but our app is commercial and it costs $30 dollars for commercial use.

**Comment by Noble-Mushtak** [comment]
Item 1 has been implemented in https://github.com/brianjaustin/permitlog-android/commit/c0744d73dd86e6a48ee3b8de7a2f4b1518428824. I will implement 2 once Nathan commits his changes with adding more states since I don't want to cause a conflict between my commit and his commit.

**Comment by brianjaustin** [comment]
I've used [this generator](https://www.iubenda.com/) in the past, and it has a free option (which I think works for commercial apps as well).

**Comment by nkizz** [comment]
I just committed my multi-state code, so @Noble-Mushtak can get started. Feel free to look around for bugs/improvements in the commit too.

**Comment by Noble-Mushtak** [comment]
Thanks, Nathan!

**Comment by Noble-Mushtak** [comment]
I have made the driver license optional. When the user does not enter the license number when adding a driver, the space in the form is just left blank so when the user prints it, they can enter the license number by hand.

**Comment by nkizz** [comment]
I used the site at the bottom of the policy to generate one, do you think we can use it? I double checked and you can use it for commercial apps. I have the HTML version on my computer, but Github wouldn't let me upload it :/
[privacy_policy.pdf](https://github.com/brianjaustin/permitlog-android/files/1273337/privacy_policy.pdf)

**Comment by Noble-Mushtak** [comment]
This looks great! However, there is one problem:

 > If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.

You did not actually include the teamredundancyteam e-mail in the Privacy Policy, so how will they know where to contact us? Other than that, I think this is really good!

**Comment by nkizz** [comment]
I forgot to metion, firebase has transport and server-side encryption. The only place it's not encrypted is on the phone, but since Android has app sandboxing, only superuser apps can access the data, so that should be fine. Good to close the issue?

**Comment by Noble-Mushtak** [comment]
I know Firebase has encryption, but we as developers can access the data unencrypted. I really think that we shouldn't have access to such personal info in case we mishandle it when exporting it or something, but at the same time, I really don't know how to fix that. I don't think it's a major issue, but it's just somewhat unsettling that we have access to so many unencrypted driver license numbers.

If you want to close the issue, though, I understand because I don't know what else we can do right now.
