### ISSUE TITLE
Fix The Current Database Entries

### ISSUE THREAD

**Issue by Noble-Mushtak** [brianjaustin/permitlog-android#45]
Nathan added some features to the database in the multistate code:

 * `weather` and `adverse` properties in the logs
 * `weather`, `adverse`, and `stateName` in the goals

Are there any properties I missed from here? I will just edit the existing entries to have 0 for weather and adverse and "Maine" for stateName.

**Comment by nkizz** [comment]
I dont know if this is possible, but would it be possible to make it so if
they have the default hours their state is set to Maine, and if they don't
then it's set to custom?

**Comment by nkizz** [comment]
Also, be sure any changes don't conflict with people who haven't upgraded
the app yet

**Comment by Noble-Mushtak** [comment]
I just realized I don't actually have to update the existing database entries. I can just make the program detect if people do not have `weather` and then if they do not, I set `weather` to 0. Same with `adverse` and with `stateName`, if they don't have `stateName`, I can just set it to "Maine". Do you think this is a good strategy?

**Comment by nkizz** [comment]
Sounds good, and it sounds pretty easy to implement my suggestions above, if you think it's a good idea

**Comment by Noble-Mushtak** [comment]
I will implement your suggestion by checking whether or not they have the `stateName` property and if they don't, I will set the `stateName` property to Maine.

**Comment by nkizz** [comment]
Why not set the state name to "Custom" if their goals are not 70 total, 10
night?

**Comment by Noble-Mushtak** [comment]
Oh...I did not realize that "Custom" was an actual choice as a state. Thanks for the clarification! I will do that.

**Comment by Noble-Mushtak** [comment]
Also, I realize now that you are saving the goals as soon as the user picks a state. Wouldn't it make more sense to save it when the click the "Save" button?

**Comment by nkizz** [comment]
I am? Didn't mean to, please fix it if it's convenient

**Comment by Noble-Mushtak** [comment]
Is "--Select a State--" necessary? I feel like making the default position "Custom" would suffice.

**Comment by nkizz** [comment]
The reason I did that was to make it clear to the user that there are
states to choose from and they don't have to put it in manually. I think if
it was on custom by default, people would see the fields and just input the
hours manually. That would be fine until we have to start generating forms,
in which having the state is nessary.

**Comment by Noble-Mushtak** [comment]
OK, but in that case, I think we should hide all of the fields and not let them save if they are on "--Select a State--".

**Comment by nkizz** [comment]
Did I not do that? Serves me right for comitting after midnight...

**Comment by Noble-Mushtak** [comment]
I have almost finished this issue with https://github.com/brianjaustin/permitlog-android/commit/79ab6667e9fa80244667931f62dd80d5cc1540ff. However, instead of editing the user's previous logs by adding the `adverse` and `weather` properties, it is assumed they are `false` if the properties are not present. For the goals, it is assumed the `adverse` and `weather` goals are `0` if not present. The only thing left to implement is Nathan's suggestion where `stateName` needs to be set to "Maine" or "Custom" based off the current goals. I will probably do this in `HomeFragment`.

Right now, the only place where these properties are used are in `LogFragment`, so if the user comes to the Log page and they have no `stateName` property, I added a message telling them to set their state in the Goals page before exporting their logs.
