### ISSUE TITLE
Crash on opening app after time being closed

### ISSUE THREAD

**Issue by nkizz** [brianjaustin/permitlog-android#47]
The app crashed after I spent about 3 min doing other things on the phone. I lost the copy of the syslog, but the error was "Caused by: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to android.os.Bundle[]" on line 142 of MainActivity.java. Also, I can't reliably reproduce it, I suspect that's something to do with android taking the app instance out of RAM. Looks like a simple fix, but I'm not sure what to change. @Noble-Mushtak, could you take a look?

**Comment by Noble-Mushtak** [comment]
You are right, this error happens once the user goes to another activity in another app, pausing MainActivity and calling `onSaveInstanceState()`, and then returns to the app, which calls `onRestoreInstanceState()` and then leads to this error.

However, I don't understand why this error would occur. In `onSaveInstanceStarte()`, I clearly set a `Bundle[]` that is upcast to `Parceable[]` when it is saved and therefore you should be able to downcast that data from `Parceable[]` back to `Bundle[]` when it is reloaded. The only reason I can think of this happening is if `onSaveInstanceState()` is, in some scenarios, not called after the activity is paused, which causes the data to be `null` when it is reloaded and therefore can not be upcast back to `Bundle[]`. However, if `onSaveInstanceState()` is not called after the activity is paused, then that is a bug with Android not handling the app lifecycle properly, which is not something we can fix.

**Comment by nkizz** [comment]
I got this error while messing around with starting intents, and around when I got the bluetooth error, so perhaps it is connected to the app crashing when that happens. Since that error won't happen, and you have a scenario where you should be able to reproduce it and you can't, I think we can just close this issue. Feel free to re-open it if you disagree. Thanks for checking it out

**Comment by Noble-Mushtak** [comment]
From [this StackOverflow answer](https://stackoverflow.com/a/12793106/3740708):

> Note that it is important to save persistent data in onPause() instead of onSaveInstanceState(Bundle) because the latter is not part of the lifecycle callbacks, so will not be called in every situation as described in its documentation.

Thus, `onSaveInstanceState()`is not always called and we should instead either account for the scenario where `onSaveInstanceState()` is not called or save to a temporary file in the `onPause()` method to fix this issue.
